!
! Optical galvo line-scan buffer with separated PEG and PVSPLINE motion.
!
! Purpose:
! - Scan a known rectangular area line by line.
! - Acquisition is active only in the constant-speed scan segment.
! - Start acquisition and stop acquisition are triggered by two separate
!   PEG engines / outputs.
! - PEG setup is isolated from motion labels; motion is generated by PVSPLINE.
!
! ACS references used:
! - PVSPLINE + MPOINT position/velocity array examples.
! - PEG_R table-based PEG examples.
! - ACS jerk-aware distance formula from segmented-motion examples:
!     TJ = ACC / JERK
!     TA = DeltaV / ACC - TJ
!     if TA < 0: TA = 0, TJ = SQRT(DeltaV / JERK)
!     distance = (Vstart + Vend) * (TA / 2 + TJ)
!
! Main labels:
! - LineScan_Reset
! - LineScan_Run
!
! Replace / verify these parts for your real hardware:
! - LS_Config_Peg_Routing
! - LS_PEG_START_STAT / LS_PEG_STOP_STAT output bit masks
! - PEG_R output mode values if your PEG output polarity/routing differs
!

GLOBAL INT LS_AXIS_X
GLOBAL INT LS_AXIS_Y
GLOBAL INT LS_DONE
GLOBAL INT LS_ERROR
GLOBAL INT LS_ROW
GLOBAL INT LS_ROW_COUNT
GLOBAL INT LS_DIRECTION
GLOBAL INT LS_POINT_COUNT

GLOBAL REAL LS_X_MIN
GLOBAL REAL LS_X_MAX
GLOBAL REAL LS_Y_MIN
GLOBAL REAL LS_Y_MAX
GLOBAL REAL LS_LINE_PITCH

GLOBAL REAL LS_SCAN_VEL
GLOBAL REAL LS_LINE_CHANGE_VEL
GLOBAL REAL LS_ACC
GLOBAL REAL LS_DEC
GLOBAL REAL LS_JERK
GLOBAL REAL LS_EXTEND_MIN
GLOBAL REAL LS_EXTEND_MARGIN
GLOBAL REAL LS_EXTENSION
GLOBAL REAL LS_ACCEL_DISTANCE
GLOBAL REAL LS_EXTRA_LEAD_DISTANCE
GLOBAL REAL LS_ACCEL_TIME
GLOBAL REAL LS_JERK_TIME
GLOBAL REAL LS_CONST_ACC_TIME

GLOBAL REAL LS_PVS_INTERVAL_MS
GLOBAL REAL LS_PVS_DT
GLOBAL REAL LS_TIMEOUT_MS
GLOBAL REAL LS_WAIT_START

GLOBAL REAL LS_ROW_Y
GLOBAL REAL LS_LINE_START_X
GLOBAL REAL LS_LINE_END_X
GLOBAL REAL LS_ENTER_X
GLOBAL REAL LS_EXIT_X
GLOBAL REAL LS_SCAN_LENGTH
GLOBAL REAL LS_ACCEL_END_X
GLOBAL REAL LS_DECEL_START_X

GLOBAL INT LS_PEG_START_ENGINE
GLOBAL INT LS_PEG_STOP_ENGINE
GLOBAL REAL LS_PEG_START_WIDTH_MS
GLOBAL REAL LS_PEG_STOP_WIDTH_MS
GLOBAL INT LS_PEG_OUTPUT_MODE
GLOBAL INT LS_PEG_START_STAT
GLOBAL INT LS_PEG_STOP_STAT
GLOBAL INT LS_PEG_START_POUT
GLOBAL INT LS_PEG_STOP_POUT
GLOBAL INT LS_PEG_START_ROUTE
GLOBAL INT LS_PEG_STOP_ROUTE
GLOBAL INT LS_PEG_ACTIVE

GLOBAL REAL LS_PEG_START_POS(1)
GLOBAL REAL LS_PEG_STOP_POS(1)
GLOBAL INT LS_PEG_START_STAT_ARR(1)
GLOBAL INT LS_PEG_STOP_STAT_ARR(1)

GLOBAL REAL LS_ROW_Y_POS(512)
GLOBAL REAL LS_PVS_ROW(4)(4096)
GLOBAL REAL LS_PVS_CHANGE(4)(1024)

GLOBAL INT LS_I
GLOBAL INT LS_ACC_POINTS
GLOBAL INT LS_CRUISE_POINTS
GLOBAL INT LS_LEAD_CRUISE_POINTS
GLOBAL REAL LS_T
GLOBAL REAL LS_PROFILE_T
GLOBAL REAL LS_PROFILE_S
GLOBAL REAL LS_PROFILE_V
GLOBAL REAL LS_PROFILE_U
GLOBAL REAL LS_PROFILE_S1
GLOBAL REAL LS_PROFILE_V1
GLOBAL REAL LS_PROFILE_S2
GLOBAL REAL LS_PROFILE_V2
GLOBAL REAL LS_CRUISE_FRACTION
GLOBAL REAL LS_DIST_FROM_EXIT
GLOBAL REAL LS_NEXT_ROW_Y
GLOBAL REAL LS_NEXT_START_X
GLOBAL REAL LS_CHANGE_DX
GLOBAL REAL LS_CHANGE_DY
GLOBAL REAL LS_CHANGE_LENGTH
GLOBAL REAL LS_CHANGE_FRACTION
GLOBAL REAL LS_CHANGE_VX
GLOBAL REAL LS_CHANGE_VY
GLOBAL INT LS_CHANGE_POINTS

LineScan_Reset:
    LS_DONE = 0
    LS_ERROR = 0
    LS_ROW = 0
    LS_DIRECTION = 1
    LS_POINT_COUNT = 0
    LS_PEG_ACTIVE = 0

    if LS_AXIS_X < 0
        LS_AXIS_X = 0
    end
    if LS_AXIS_Y < 0
        LS_AXIS_Y = 1
    end
    if LS_LINE_PITCH <= 0
        LS_LINE_PITCH = 1
    end
    if LS_SCAN_VEL <= 0
        LS_SCAN_VEL = 50
    end
    if LS_LINE_CHANGE_VEL <= 0
        LS_LINE_CHANGE_VEL = LS_SCAN_VEL
    end
    if LS_ACC <= 0
        LS_ACC = LS_SCAN_VEL * 10
    end
    if LS_DEC <= 0
        LS_DEC = LS_ACC
    end
    if LS_JERK <= 0
        LS_JERK = LS_ACC * 10
    end
    if LS_EXTEND_MARGIN < 0
        LS_EXTEND_MARGIN = 0
    end
    if LS_PVS_INTERVAL_MS <= 0
        LS_PVS_INTERVAL_MS = 2
    end
    if LS_TIMEOUT_MS <= 0
        LS_TIMEOUT_MS = 30000
    end

    if LS_PEG_START_ENGINE <= 0
        LS_PEG_START_ENGINE = 1
    end
    if LS_PEG_STOP_ENGINE <= 0
        LS_PEG_STOP_ENGINE = 2
    end
    if LS_PEG_START_WIDTH_MS <= 0
        LS_PEG_START_WIDTH_MS = 0.001
    end
    if LS_PEG_STOP_WIDTH_MS <= 0
        LS_PEG_STOP_WIDTH_MS = 0.001
    end
    if LS_PEG_START_STAT = 0
        LS_PEG_START_STAT = 0b0001
    end
    if LS_PEG_STOP_STAT = 0
        LS_PEG_STOP_STAT = 0b0010
    end
    if LS_PEG_START_POUT <= 0
        LS_PEG_START_POUT = 1
    end
    if LS_PEG_STOP_POUT <= 0
        LS_PEG_STOP_POUT = 2
    end
STOP

LineScan_Run:
    LS_DONE = 0
    LS_ERROR = 0
    LS_ROW = 0
    LS_PEG_ACTIVE = 0

    CALL LS_Validate_Config
    if LS_ERROR <> 0
        goto LS_Error
    end

    CALL LS_Calc_Extension
    CALL LS_Build_Row_Table
    CALL LS_Set_Motion_Params
    CALL LS_Config_Peg_Routing

    ENABLE (LS_AXIS_X, LS_AXIS_Y)
    CALL LS_Move_To_First_Row
    if LS_ERROR <> 0
        goto LS_Error
    end

    LS_ROW = 0
    while LS_ROW < LS_ROW_COUNT
        CALL LS_Prepare_Row

        CALL LS_Arm_Row_Pegs
        if LS_ERROR <> 0
            goto LS_Error
        end

        CALL LS_Build_Row_PVSPLINE
        if LS_ERROR <> 0
            goto LS_Error
        end

        CALL LS_Run_Row_PVSPLINE
        if LS_ERROR <> 0
            goto LS_Error
        end

        CALL LS_Stop_Pegs

        if LS_ROW + 1 < LS_ROW_COUNT
            CALL LS_Run_Line_Change_PVSPLINE
            if LS_ERROR <> 0
                goto LS_Error
            end
        end

        LS_ROW = LS_ROW + 1
    end

    CALL LS_Stop_Pegs
    LS_DONE = 1
STOP

LS_Validate_Config:
    if LS_X_MAX <= LS_X_MIN
        LS_ERROR = 101
        RET
    end
    if LS_Y_MAX < LS_Y_MIN
        LS_ERROR = 102
        RET
    end
    if LS_LINE_PITCH <= 0
        LS_ERROR = 103
        RET
    end
    if LS_SCAN_VEL <= 0
        LS_ERROR = 104
        RET
    end
    if LS_ACC <= 0
        LS_ERROR = 105
        RET
    end
    if LS_DEC <= 0
        LS_ERROR = 106
        RET
    end
    if LS_JERK <= 0
        LS_ERROR = 107
        RET
    end
    if LS_PVS_INTERVAL_MS <= 0
        LS_ERROR = 108
        RET
    end
    LS_ERROR = 0
RET

LS_Calc_Extension:
    LS_PVS_DT = LS_PVS_INTERVAL_MS / 1000

    LS_JERK_TIME = LS_ACC / LS_JERK
    LS_CONST_ACC_TIME = (LS_SCAN_VEL / LS_ACC) - LS_JERK_TIME

    if LS_CONST_ACC_TIME < 0
        LS_CONST_ACC_TIME = 0
        LS_JERK_TIME = SQRT(LS_SCAN_VEL / LS_JERK)
    end

    LS_ACCEL_TIME = (2 * LS_JERK_TIME) + LS_CONST_ACC_TIME
    LS_ACCEL_DISTANCE = LS_SCAN_VEL * ((LS_CONST_ACC_TIME / 2) + LS_JERK_TIME)
    LS_EXTENSION = LS_ACCEL_DISTANCE + LS_EXTEND_MARGIN

    if LS_EXTENSION < LS_EXTEND_MIN
        LS_EXTENSION = LS_EXTEND_MIN
    end
    if LS_EXTENSION <= 0
        LS_EXTENSION = LS_LINE_PITCH
    end
    LS_EXTRA_LEAD_DISTANCE = LS_EXTENSION - LS_ACCEL_DISTANCE
    if LS_EXTRA_LEAD_DISTANCE < 0
        LS_EXTRA_LEAD_DISTANCE = 0
    end

    LS_ROW_COUNT = ((LS_Y_MAX - LS_Y_MIN) / LS_LINE_PITCH) + 1
    if LS_ROW_COUNT < 1
        LS_ROW_COUNT = 1
    end
    if LS_ROW_COUNT > 512
        LS_ROW_COUNT = 512
    end
RET

LS_Build_Row_Table:
    LS_I = 0
    while LS_I < LS_ROW_COUNT
        LS_ROW_Y_POS(LS_I) = LS_Y_MIN + (LS_I * LS_LINE_PITCH)
        if LS_ROW_Y_POS(LS_I) > LS_Y_MAX
            LS_ROW_Y_POS(LS_I) = LS_Y_MAX
        end
        LS_I = LS_I + 1
    end
RET

LS_Set_Motion_Params:
    VEL(LS_AXIS_X) = LS_SCAN_VEL
    ACC(LS_AXIS_X) = LS_ACC
    DEC(LS_AXIS_X) = LS_DEC
    JERK(LS_AXIS_X) = LS_JERK
    KDEC(LS_AXIS_X) = LS_DEC

    VEL(LS_AXIS_Y) = LS_LINE_CHANGE_VEL
    ACC(LS_AXIS_Y) = LS_ACC
    DEC(LS_AXIS_Y) = LS_DEC
    JERK(LS_AXIS_Y) = LS_JERK
    KDEC(LS_AXIS_Y) = LS_DEC
RET

LS_Config_Peg_Routing:
    !
    ! Example routing based on ACS PEG examples.
    ! ASSIGNPEG axis, 0b011, ... assigns PEG engines 1 and 2 to the scan
    ! encoder. Adjust if your controller maps PEG engines differently.
    !
    ASSIGNPEG LS_AXIS_X, 0b011, 0b0000

    ! Route PEG engine pulses to two separate physical PEG outputs.
    ! Defaults: engine/output 1 = acquisition start, engine/output 2 = stop.
    ASSIGNPOUTS LS_PEG_START_ENGINE, LS_PEG_START_POUT, LS_PEG_START_ROUTE
    ASSIGNPOUTS LS_PEG_STOP_ENGINE, LS_PEG_STOP_POUT, LS_PEG_STOP_ROUTE
RET

LS_Move_To_First_Row:
    LS_ROW = 0
    CALL LS_Prepare_Row

    PTP (LS_AXIS_X, LS_AXIS_Y), LS_LINE_START_X, LS_ROW_Y
    CALL LS_Wait_Inpos
RET

LS_Prepare_Row:
    LS_ROW_Y = LS_ROW_Y_POS(LS_ROW)

    if (LS_ROW % 2) = 0
        LS_DIRECTION = 1
        LS_ENTER_X = LS_X_MIN
        LS_EXIT_X = LS_X_MAX
        LS_LINE_START_X = LS_X_MIN - LS_EXTENSION
        LS_LINE_END_X = LS_X_MAX + LS_EXTENSION
    else
        LS_DIRECTION = -1
        LS_ENTER_X = LS_X_MAX
        LS_EXIT_X = LS_X_MIN
        LS_LINE_START_X = LS_X_MAX + LS_EXTENSION
        LS_LINE_END_X = LS_X_MIN - LS_EXTENSION
    end

    LS_SCAN_LENGTH = ABS(LS_X_MAX - LS_X_MIN)
RET

LS_Arm_Row_Pegs:
    CALL LS_Stop_Pegs

    LS_PEG_START_POS(0) = LS_ENTER_X
    LS_PEG_STOP_POS(0) = LS_EXIT_X
    LS_PEG_START_STAT_ARR(0) = LS_PEG_START_STAT
    LS_PEG_STOP_STAT_ARR(0) = LS_PEG_STOP_STAT

    ! PEG setup only. No motion commands in this label.
    PEG_R LS_PEG_START_ENGINE, LS_PEG_START_WIDTH_MS, LS_PEG_OUTPUT_MODE, 0, 0, LS_PEG_START_POS, LS_PEG_START_STAT_ARR
    PEG_R LS_PEG_STOP_ENGINE, LS_PEG_STOP_WIDTH_MS, LS_PEG_OUTPUT_MODE, 0, 0, LS_PEG_STOP_POS, LS_PEG_STOP_STAT_ARR

    TILL AST(LS_PEG_START_ENGINE).#PEGREADY
    TILL AST(LS_PEG_STOP_ENGINE).#PEGREADY
    LS_PEG_ACTIVE = 1
RET

LS_Stop_Pegs:
    STOPPEG LS_PEG_START_ENGINE
    STOPPEG LS_PEG_STOP_ENGINE
    LS_PEG_ACTIVE = 0
RET

LS_Build_Row_PVSPLINE:
    LS_POINT_COUNT = 0
    LS_ACC_POINTS = CEIL(LS_ACCEL_TIME / LS_PVS_DT)
    if LS_ACC_POINTS < 2
        LS_ACC_POINTS = 2
    end

    LS_CRUISE_POINTS = CEIL(LS_SCAN_LENGTH / (LS_SCAN_VEL * LS_PVS_DT))
    if LS_CRUISE_POINTS < 2
        LS_CRUISE_POINTS = 2
    end

    LS_LEAD_CRUISE_POINTS = CEIL(LS_EXTRA_LEAD_DISTANCE / (LS_SCAN_VEL * LS_PVS_DT))
    if (LS_EXTRA_LEAD_DISTANCE > 0) & (LS_LEAD_CRUISE_POINTS < 1)
        LS_LEAD_CRUISE_POINTS = 1
    end

    if ((2 * LS_ACC_POINTS) + LS_CRUISE_POINTS + (2 * LS_LEAD_CRUISE_POINTS) + 1) > 4096
        LS_ERROR = 201
        RET
    end

    LS_ACCEL_END_X = LS_LINE_START_X + (LS_DIRECTION * LS_ACCEL_DISTANCE)
    LS_DECEL_START_X = LS_EXIT_X + (LS_DIRECTION * LS_EXTRA_LEAD_DISTANCE)

    ! Acceleration from lead-in start to commanded scan velocity.
    LS_I = 0
    while LS_I <= LS_ACC_POINTS
        LS_PROFILE_T = LS_I * LS_PVS_DT
        if LS_PROFILE_T > LS_ACCEL_TIME
            LS_PROFILE_T = LS_ACCEL_TIME
        end
        CALL LS_Calc_Accel_Profile

        LS_PVS_ROW(0)(LS_POINT_COUNT) = LS_LINE_START_X + (LS_DIRECTION * LS_PROFILE_S)
        LS_PVS_ROW(1)(LS_POINT_COUNT) = LS_ROW_Y
        LS_PVS_ROW(2)(LS_POINT_COUNT) = LS_DIRECTION * LS_PROFILE_V
        LS_PVS_ROW(3)(LS_POINT_COUNT) = 0
        LS_POINT_COUNT = LS_POINT_COUNT + 1

        LS_I = LS_I + 1
    end

    ! Optional extra lead-in at constant speed. This absorbs margin or a
    ! user-forced minimum extension while preserving the scan-area entry speed.
    LS_I = 1
    while LS_I <= LS_LEAD_CRUISE_POINTS
        LS_CRUISE_FRACTION = LS_I / LS_LEAD_CRUISE_POINTS
        LS_PVS_ROW(0)(LS_POINT_COUNT) = LS_ACCEL_END_X + (LS_DIRECTION * LS_EXTRA_LEAD_DISTANCE * LS_CRUISE_FRACTION)
        LS_PVS_ROW(1)(LS_POINT_COUNT) = LS_ROW_Y
        LS_PVS_ROW(2)(LS_POINT_COUNT) = LS_DIRECTION * LS_SCAN_VEL
        LS_PVS_ROW(3)(LS_POINT_COUNT) = 0
        LS_POINT_COUNT = LS_POINT_COUNT + 1

        LS_I = LS_I + 1
    end

    ! Constant-speed scan segment. Acquisition is active only here.
    LS_I = 1
    while LS_I <= LS_CRUISE_POINTS
        LS_CRUISE_FRACTION = LS_I / LS_CRUISE_POINTS
        LS_PVS_ROW(0)(LS_POINT_COUNT) = LS_ENTER_X + (LS_DIRECTION * LS_SCAN_LENGTH * LS_CRUISE_FRACTION)
        LS_PVS_ROW(1)(LS_POINT_COUNT) = LS_ROW_Y
        LS_PVS_ROW(2)(LS_POINT_COUNT) = LS_DIRECTION * LS_SCAN_VEL
        LS_PVS_ROW(3)(LS_POINT_COUNT) = 0
        LS_POINT_COUNT = LS_POINT_COUNT + 1

        LS_I = LS_I + 1
    end

    ! Optional extra lead-out at constant speed before deceleration starts.
    LS_I = 1
    while LS_I <= LS_LEAD_CRUISE_POINTS
        LS_CRUISE_FRACTION = LS_I / LS_LEAD_CRUISE_POINTS
        LS_PVS_ROW(0)(LS_POINT_COUNT) = LS_EXIT_X + (LS_DIRECTION * LS_EXTRA_LEAD_DISTANCE * LS_CRUISE_FRACTION)
        LS_PVS_ROW(1)(LS_POINT_COUNT) = LS_ROW_Y
        LS_PVS_ROW(2)(LS_POINT_COUNT) = LS_DIRECTION * LS_SCAN_VEL
        LS_PVS_ROW(3)(LS_POINT_COUNT) = 0
        LS_POINT_COUNT = LS_POINT_COUNT + 1

        LS_I = LS_I + 1
    end

    ! Deceleration from lead-out cruise end to final row end.
    LS_I = 1
    while LS_I <= LS_ACC_POINTS
        LS_T = LS_I * LS_PVS_DT
        if LS_T > LS_ACCEL_TIME
            LS_T = LS_ACCEL_TIME
        end

        LS_PROFILE_T = LS_ACCEL_TIME - LS_T
        CALL LS_Calc_Accel_Profile
        LS_DIST_FROM_EXIT = LS_ACCEL_DISTANCE - LS_PROFILE_S

        LS_PVS_ROW(0)(LS_POINT_COUNT) = LS_DECEL_START_X + (LS_DIRECTION * LS_DIST_FROM_EXIT)
        LS_PVS_ROW(1)(LS_POINT_COUNT) = LS_ROW_Y
        LS_PVS_ROW(2)(LS_POINT_COUNT) = LS_DIRECTION * LS_PROFILE_V
        LS_PVS_ROW(3)(LS_POINT_COUNT) = 0
        LS_POINT_COUNT = LS_POINT_COUNT + 1

        LS_I = LS_I + 1
    end

    if LS_POINT_COUNT < 2
        LS_ERROR = 202
    end
RET

LS_Calc_Accel_Profile:
    !
    ! Output:
    ! - LS_PROFILE_S: distance from rest to current time
    ! - LS_PROFILE_V: velocity at current time
    !
    if LS_CONST_ACC_TIME = 0
        if LS_PROFILE_T <= LS_JERK_TIME
            LS_PROFILE_V = 0.5 * LS_JERK * LS_PROFILE_T * LS_PROFILE_T
            LS_PROFILE_S = LS_JERK * LS_PROFILE_T * LS_PROFILE_T * LS_PROFILE_T / 6
        else
            LS_PROFILE_U = LS_PROFILE_T - LS_JERK_TIME
            LS_PROFILE_V1 = 0.5 * LS_JERK * LS_JERK_TIME * LS_JERK_TIME
            LS_PROFILE_S1 = LS_JERK * LS_JERK_TIME * LS_JERK_TIME * LS_JERK_TIME / 6
            LS_PROFILE_V = LS_PROFILE_V1 + (LS_JERK * LS_JERK_TIME * LS_PROFILE_U) - (0.5 * LS_JERK * LS_PROFILE_U * LS_PROFILE_U)
            LS_PROFILE_S = LS_PROFILE_S1 + (LS_PROFILE_V1 * LS_PROFILE_U) + (0.5 * LS_JERK * LS_JERK_TIME * LS_PROFILE_U * LS_PROFILE_U) - (LS_JERK * LS_PROFILE_U * LS_PROFILE_U * LS_PROFILE_U / 6)
        end
    else
        if LS_PROFILE_T <= LS_JERK_TIME
            LS_PROFILE_V = 0.5 * LS_JERK * LS_PROFILE_T * LS_PROFILE_T
            LS_PROFILE_S = LS_JERK * LS_PROFILE_T * LS_PROFILE_T * LS_PROFILE_T / 6
        else
            if LS_PROFILE_T <= (LS_JERK_TIME + LS_CONST_ACC_TIME)
                LS_PROFILE_U = LS_PROFILE_T - LS_JERK_TIME
                LS_PROFILE_V1 = 0.5 * LS_JERK * LS_JERK_TIME * LS_JERK_TIME
                LS_PROFILE_S1 = LS_JERK * LS_JERK_TIME * LS_JERK_TIME * LS_JERK_TIME / 6
                LS_PROFILE_V = LS_PROFILE_V1 + (LS_ACC * LS_PROFILE_U)
                LS_PROFILE_S = LS_PROFILE_S1 + (LS_PROFILE_V1 * LS_PROFILE_U) + (0.5 * LS_ACC * LS_PROFILE_U * LS_PROFILE_U)
            else
                LS_PROFILE_U = LS_PROFILE_T - LS_JERK_TIME - LS_CONST_ACC_TIME
                LS_PROFILE_V1 = 0.5 * LS_JERK * LS_JERK_TIME * LS_JERK_TIME
                LS_PROFILE_S1 = LS_JERK * LS_JERK_TIME * LS_JERK_TIME * LS_JERK_TIME / 6
                LS_PROFILE_V2 = LS_PROFILE_V1 + (LS_ACC * LS_CONST_ACC_TIME)
                LS_PROFILE_S2 = LS_PROFILE_S1 + (LS_PROFILE_V1 * LS_CONST_ACC_TIME) + (0.5 * LS_ACC * LS_CONST_ACC_TIME * LS_CONST_ACC_TIME)
                LS_PROFILE_V = LS_PROFILE_V2 + (LS_ACC * LS_PROFILE_U) - (0.5 * LS_JERK * LS_PROFILE_U * LS_PROFILE_U)
                LS_PROFILE_S = LS_PROFILE_S2 + (LS_PROFILE_V2 * LS_PROFILE_U) + (0.5 * LS_ACC * LS_PROFILE_U * LS_PROFILE_U) - (LS_JERK * LS_PROFILE_U * LS_PROFILE_U * LS_PROFILE_U / 6)
            end
        end
    end

    if LS_PROFILE_T >= LS_ACCEL_TIME
        LS_PROFILE_V = LS_SCAN_VEL
        LS_PROFILE_S = LS_ACCEL_DISTANCE
    end
RET

LS_Run_Row_PVSPLINE:
    PVSPLINE (LS_AXIS_X, LS_AXIS_Y), LS_PVS_INTERVAL_MS
    MPOINT (LS_AXIS_X, LS_AXIS_Y), LS_PVS_ROW, LS_POINT_COUNT
    ENDS (LS_AXIS_X, LS_AXIS_Y)
    CALL LS_Wait_Inpos
RET

LS_Run_Line_Change_PVSPLINE:
    LS_NEXT_ROW_Y = LS_ROW_Y_POS(LS_ROW + 1)

    if ((LS_ROW + 1) % 2) = 0
        LS_NEXT_START_X = LS_X_MIN - LS_EXTENSION
    else
        LS_NEXT_START_X = LS_X_MAX + LS_EXTENSION
    end

    LS_CHANGE_DX = LS_NEXT_START_X - LS_LINE_END_X
    LS_CHANGE_DY = LS_NEXT_ROW_Y - LS_ROW_Y
    LS_CHANGE_LENGTH = HYPOT(LS_CHANGE_DX, LS_CHANGE_DY)

    if LS_CHANGE_LENGTH <= 0
        RET
    end

    LS_CHANGE_POINTS = CEIL(LS_CHANGE_LENGTH / (LS_LINE_CHANGE_VEL * LS_PVS_DT))
    if LS_CHANGE_POINTS < 2
        LS_CHANGE_POINTS = 2
    end
    if LS_CHANGE_POINTS > 1024
        LS_ERROR = 203
        RET
    end

    LS_CHANGE_VX = (LS_CHANGE_DX / LS_CHANGE_LENGTH) * LS_LINE_CHANGE_VEL
    LS_CHANGE_VY = (LS_CHANGE_DY / LS_CHANGE_LENGTH) * LS_LINE_CHANGE_VEL

    LS_I = 0
    while LS_I < LS_CHANGE_POINTS
        LS_CHANGE_FRACTION = LS_I / (LS_CHANGE_POINTS - 1)
        LS_PVS_CHANGE(0)(LS_I) = LS_LINE_END_X + (LS_CHANGE_DX * LS_CHANGE_FRACTION)
        LS_PVS_CHANGE(1)(LS_I) = LS_ROW_Y + (LS_CHANGE_DY * LS_CHANGE_FRACTION)

        if (LS_I = 0) | (LS_I = LS_CHANGE_POINTS - 1)
            LS_PVS_CHANGE(2)(LS_I) = 0
            LS_PVS_CHANGE(3)(LS_I) = 0
        else
            LS_PVS_CHANGE(2)(LS_I) = LS_CHANGE_VX
            LS_PVS_CHANGE(3)(LS_I) = LS_CHANGE_VY
        end

        LS_I = LS_I + 1
    end

    PVSPLINE (LS_AXIS_X, LS_AXIS_Y), LS_PVS_INTERVAL_MS
    MPOINT (LS_AXIS_X, LS_AXIS_Y), LS_PVS_CHANGE, LS_CHANGE_POINTS
    ENDS (LS_AXIS_X, LS_AXIS_Y)
    CALL LS_Wait_Inpos
RET

LS_Wait_Inpos:
    LS_WAIT_START = TIME
    while (MST(LS_AXIS_X).#INPOS = 0) | (MST(LS_AXIS_Y).#INPOS = 0)
        if (TIME - LS_WAIT_START) > LS_TIMEOUT_MS
            LS_ERROR = 301
            RET
        end
        WAIT 5
    end
RET

LS_Error:
    CALL LS_Stop_Pegs
    LS_DONE = -1
STOP
